using QuiverLauncher.Models;
namespace QuiverLauncher.Views;
public enum LibraryActionKind
{
    AddToSteam,
    AutoUpdateMenu,
    BackToVerifiedUpdates,
    ChangeVersion,
    ConfigureWindowsRunner,
    CreateShortcut,
    DeleteGameFromLibrary,
    EditCustomDisplayNameMenu,
    EditGameEntry,
    EditTagsMenu,
    EmptyLibraryAddApp,
    EmptyLibraryBrowseCatalog,
    HideGame,
    InstallUnverifiedRelease,
    LaunchGameMenu,
    LibrarySearchClear,
    LocateExistingInstall,
    OpenFolder,
    OpenGitHubPage,
    OpenMods,
    Reinstall,
    RemoveCustomIcon,
    RemoveGameEntry,
    SelectDifferentExecutable,
    SetCustomIcon,
    ShowChangelog,
    ShowReadme,
    SkipUpdate,
    UpdateNowMenu,
}
