<Project Sdk="Microsoft.NET.Sdk">
	<PropertyGroup>
		<OutputType>Exe</OutputType>
		<TargetFramework>net10.0-android</TargetFramework>
		<SupportedOSPlatformVersion>24</SupportedOSPlatformVersion>
		<Nullable>enable</Nullable>
		<ImplicitUsings>enable</ImplicitUsings>
		<ApplicationId>com.quiverlauncher.app</ApplicationId>
		<ApplicationVersion>322</ApplicationVersion>
		<ApplicationDisplayVersion>3.2.1</ApplicationDisplayVersion>
		<AndroidPackageFormat>apk</AndroidPackageFormat>
		<EmbedAssembliesIntoApk>true</EmbedAssembliesIntoApk>
		<RootNamespace>QuiverLauncher.Android</RootNamespace>
		<AssemblyName>QuiverLauncher.Android</AssemblyName>
	</PropertyGroup>

	<ItemGroup>
		<PackageReference Include="Avalonia.Android" Version="12.1.1" />
		<PackageReference Include="Avalonia.Fonts.Inter" Version="12.1.1" />
	</ItemGroup>

	<ItemGroup>
		<ProjectReference Include="..\QuiverLauncher.App.csproj" />
	</ItemGroup>
</Project>
